apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mychart.name" . }}
    helm.sh/chart: {{ include "mychart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{ if eq .Values.service.type "LoadBalancer" }}
  # For a deployment in transit, this is needed:
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  {{ end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "mychart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
